#!/bin/bash

# find the plotting program
if [ -e corr.py ]
then
    python corr.py "$@"
else
    if [ -e ~/Research/analyze/corr.py ]
    then
       python ~/Research/analyze/corr.py "$@"
    fi     
fi
