#!/bin/bash

# find the plotting program
if [ -e e.py ]
then
    python e.py "$@"
else
    if [ -e ~/Research/analyze/e.py ]
    then
       python ~/Research/analyze/e.py "$@"
    else
	if [ -e ~/bin/e.py ]
	then
	    python ~/bin/e.py "$@"
	fi
    fi
fi
