#!/bin/bash

# find the plotting program
if [ -e fft.py ]
then
    python fft.py "$@"
else
    if [ -e ~/Research/analyze/fft.py ]
    then
       python ~/Research/analyze/fft.py "$@"
    else
        if [ -e ~/bin/fft.py ]
	then
	    python ~/bin/fft.py "$@"
	fi
    fi     
fi
