#!/bin/bash

# find the plotting program
if [ -e fix.py ]
then
    python fix.py "$@"
else
    if [ -e ~/Research/analyze/fix.py ]
    then
       python ~/Research/analyze/fix.py "$@"
    fi     
fi
