#!/bin/bash

# find the foldmany program
if [ -e foldmany.py ]
then
    python foldmany.py "$@"
else
    if [ -e ~/Research/analyze/foldmany.py ]
    then
       python ~/Research/analyze/foldmany.py "$@"
    else
	if [ -e ~/bin/foldmany.py ]
	then
	    python ~/bin/foldmany.py "$@"
	fi
    fi     
fi
