#!/bin/bash
# Script to run through a day's observations and save integrated intensities
# HISTORY
# 20APR23 GIL initial version

export archivehome=~/archive

if [ -z "$1" ]
then
    echo "oneday: Calibrate and log integrated intensities for one day of observation"
    echo "usage: oneday <day> <YearMonth>"
    echo "where <day> 	Daynumber matching directory name ie the 9th is 09"
    echo "where <YearMonth> is optional year month, if not the current default"
    echo "for example:"
    echo "ondday 09 20Apr"
    echo ""
    echo "To process all data from the 9th of April 2020"
    echo ""
    exit -1
else
# ie export DAY=08
    export DAY=$1
fi

if [ -z "$2" ]
then
    export YearMonth="20Apr"
else
    export YearMonth=$2
fi    

export ADATE=$YearMonth$DAY
echo "Summarizing all observations from day $ADATE"
export HOT=../T2-20-04-09T071901.hot 
export COLD=../T2-20-04-09T053503.cld
export PI=2; cd pi$PI-data-$ADATE;  T -A $HOT $COLD -K -N 0 -B -F 1 -I $PI 600. *.ast; cd ..
export HOT=../T3-20-04-12T091240.hot
export COLD=../T3-20-04-15T162151.cld
export PI=3; cd pi$PI-data-$ADATE;  T -A $HOT $COLD -K -N 0 -B -F 1 -I $PI 600. *.ast; cd ..
export HOT=../T4-20-04-12T091258.hot
export COLD=../T4-20-04-15T162217.cld
export PI=4; cd pi$PI-data-$ADATE;  T -A $HOT $COLD -K -N 0 -B -F 1 -I $PI 600. *.ast; cd ..
export HOT=../T5-20-04-12T090254.hot
export COLD=../T5-20-04-11T163028.cld
export PI=5; cd pi$PI-data-$ADATE;  T -A $HOT $COLD -K -N 0 -B -F 1 -I $PI 600. *.ast; cd ..
