#!/bin/bash
# find the latest observation in standard directory
# HISTORY
# 20Jun16 GIL initial version that finds the latest observation
# find the most recent note file 

export datadir=/home/pi/Research/gr-radio_astro/data

cd $datadir
export files=`ls -1 2*.ast 2> /dev/null | tail -1`
export latestobs=`echo $files | awk '{print $1}'` 2> /dev/null
echo $latestobs

#head -40 $latest | grep "# AZ" | awk '{ print $4}'

