#!/bin/bash

# find the most recent note file 
#head -40 $1 | grep "# AZ" 

export obshome=~/Research/gr-radio_astro/examples

export files=`ls -t *.not 2> /dev/null`
export latest=`echo $files | awk '{print $1}'` 2> /dev/null

if [ "$latest" = "" ];
then
    export files=`ls -t $obshome/*.not 2> /dev/null`
    export latest=`echo $files | awk '{print $1}'` 2> /dev/null
fi

echo $latest

if [ "$latest" = "" ];
then
    echo "Can not find a Note File!" 
    echo "Please change directory to where you started your observations"
else
    export latestaz=`head -80 $latest | grep "# AZ " | awk '{ print $4 }'`
    export latestel=`head -80 $latest | grep "# EL " | awk '{ print $4 }'`

    # finally print the telescope coordinates (in degrees)
    echo $latestaz $latestel
fi




