#!/bin/bash
# find the latest note file
# HISTORY
# 19MAY10 GIL initial version
# find the most recent note file 
#head -40 $1 | grep "# AZ" 

export files=`ls -t *.not 2> /dev/null`
export latest=`echo $files | awk '{print $1}'` 2> /dev/null
echo $latest

#head -40 $latest | grep "# AZ" | awk '{ print $4}'

