#!/bin/bash

# find the group program
if [ -e group.py ]
then
    python group.py "$@"
else
    if [ -e ~/Research/analyze/group.py ]
    then
       python ~/Research/analyze/group.py "$@"
    fi     
fi
