#!/bin/bash

# find the group program
if [ -e group.py ]
then
    python group.py "$@"
else
    if [ -e ~/Research/analyze/group.py ]
    then
       python ~/Research/analyze/group.py "$@"
    else
	if [ -e ~/bin/group.py ]
	then
	    python ~/bin/group.py "$@"
	fi     
    fi
fi
