#!/bin/bash

export PYTHONPATH=~/bin:$PYTHONPATH

# find the Local Sideral Time program
if [ -f lstClock.py ]
then
    python lstClock.py
else
    if [ -f ~/Research/analyze/lstClock.py ]
    then
       python ~/Research/analyze/lstClock.py
    else
	if [ -f ~/bin/lstClock.py ]
	then
	    python ~/bin/lstClock.py
	fi
    fi
fi
