#!/bin/bash
#Median filter calibrate Horn Astronomy data
#HISTORY
#18DEC10 GIL 1st version with comments


# if the python program is local, execute it
if [ -e ./m.py ]
then
   python ./m.py "$@"
else
# if python is in the bin directory, execute that
    if [ -e ~/bin/m.py ]
    then
	python ~/bin/m.py "$@"
    else
	if [ -e ~/Research/analyze/m.py ]
	then
       	    python ~/Research/analyze/m.py "$@"
	else  
	    echo "Can not find Median baseline plotting python program: m.py" 
	fi
    fi
fi  # end else not in current directory
