#!/bin/bash

# Daily look for yesterday's matchs

cd /media/karl

export analyze=~/Research/analyze
export dateToSort=`$analyze/Yesterday`
export mylog=/home/karl/eventlog
export matchkeys="-Q -ND 144 -N 3 -L "$mylog" -G -O 1 -C "$dateToSort

echo "Matching events from date: " $dateToSort
echo "Using these Match params : " $matchkeys

# find the matchevent program
if [ -e matchevents.py ]
then
    python matchevents.py $matchkeys 
else
    if [ -e ~/Research/analyze/matchevents.py ]
    then
       python ~/Research/analyze/matchevents.py $matchkeys
    else 
	if [ -e ~/bin/matchevents.py ]
	then
	    python ~/bin/matchevents.py $matchkeys
	fi
    fi     
fi
