#!/bin/bash

# find the matchevent program
if [ -e matchevent.py ]
then
    python matchevent.py "$@"
else
    if [ -e ~/Research/analyze/matchevents.py ]
    then
       python ~/Research/analyze/matchevents.py "$@"
    else 
	if [ -e ~/bin/matchevents.py ]
	then
	    python ~/bin/matchevents.py "$@"
	fi
    fi     
fi
