#!/bin/bash
# plot the latest observation compared to latest hot
# HISTORY
# 20Dec24 GIL check for no hot and create latest file in html directory
# 20Nov12 GIL create latest file in html directory
# 20Jun16 GIL initial version that finds the latest observation
# find the most recent note file 

export datadir=/home/pi/Research/gr-radio_astro/data
export lastestdir=/var/www/html/latest
export grhome=/home/pi/Research/gr-radio_astro

export binhome=/home/pi/Research/analyze
export latesthot=`$binhome/getlatesthot`
export latestobs=`$binhome/getlatestobs`
export latestdir="/var/www/html/latest"
# go to one directory above the data dir
cd $grhome
if [ "$latesthot" != "" ] ; then
    export latesthot=data/$latesthot
    sudo cp -f $latesthot $latestdir/latest.hot
fi
if [ "$latestobs" != "" ] ; then
    export latestobs=data/$latestobs
    sudo cp -f $latestobs $latestdir/latest.ast
fi

if [ "$latestobs" == "" ] && [ "$latesthot" == "" ] ; then
    exit
fi

cd $latestdir
echo $latesthot $latestobs
$binhome/R -P ./ *.hot *.ast

export latestpng=`ls -1 $latestdir/R-2*.png | tail -1`
if [ -f $latestpng ] ; then 
    sudo mv -f $latestpng R-latest.png
    sudo chown pi R-latest.png
fi

# link the latest png for easy access to web page
export latestpdf=$latestdir/R-latest.pdf
if [ -f  $latestpdf ] ; then
    sudo mv -f $newestpdf R-latest.pdf
    sudo chown pi R-latest.pdf
fi    

