#!/bin/bash
#Return Date from GPS device, if it is running
#HISTORY
#20SEP28 GIL get date from gps
GPSDATE=`gpspipe -w | head -10 | grep TPV | sed -r 's/.*"time":"([^"]*)".*/\1/' | head -1` 


#GPSOFFSET=`gpspipe -w | head -10 | grep TPV | sed -r 's/.*"eps":"([^"]*)".*/\1/' | head -1` 

#echo $GPSOFFSET

sudo date -s "$GPSDATE"
NEWDATE=`date +%T  --date='1 seconds'`
sudo date +%T -s "$NEWDATE"

