#!/bin/bash
#Plot Raw Horn Astronomy data
#HISTORY
#20NOV17 GIL look for analyze directory
#18MAR25 GIL Clean up documentation
#18DEC10 GIL 1st version with comments

export analyze=/home/pi/Research/analyze
# if not on a PI, look elsewhere for the analyze directory
if [ ! -d $analyze ] ; then
    export analyze=~/Research/analyze
fi

# find the plotting program
if [ -e toazel.py ]
then
    python toazel.py "$@"
else
    if [ -f $analyze/toazel.py ]
    then
	python $analyze/toazel.py "$@"
    else
       if [ -e ~/bin/toazel.py ]
       then
       	  python ~/bin/toazel.py "$@"
       else  
           print "Can not find python Az,El plotting program: toazel.py" 
       fi
    fi
fi  # end else not in current directory
