#!/bin/bash
#Abreviation for chronyc tracking time command
#HISTORY
#20Sep17 GIL use ntpq if available
#20Sep10 GIL Initial version

if [ -f /usr/bin/ntpstat ]
then
    date
    ntpstat
else
    chronyc tracking
fi



