#!/bin/bash
# plot the latest observation compared to latest hot
# HISTORY
# 20Nov12 GIL create latest file in html directory
# 20Jun16 GIL initial version that finds the latest observation
# find the most recent note file 

export datadir=/home/pi/Research/gr-radio_astro/data

export binhome=/home/pi/Research/analyze
export latesthot=`$binhome/getlatesthot`
export latestobs=`$binhome/getlatestobs`

if [ "$latesthot" == "" ] ; then
    echo "No Hot File, can not calibrate"
    exit
fi

if [ "$latestobs" == "" ] ; then
    echo "No Observation File, can not calibrate"
    exit
fi

export latestdir="/var/www/html/latest"
cd $datadir
$binhome/T -P $latestdir/ 3600. $latesthot $latestobs

# link the latest png for easy access to web page
export latestpng=$latestdir/T-latest.png
# now relink to the last latest plot
if [ -f  $latestpng ] ; then
    sudo rm $latestpng
fi

export newestpng=`ls -t $latestdir/T*.png | head -1`
#echo "Newest: " $newestpng
if [ "$newestpng" != "$latestpng" ] ; then
    sudo ln -s $newestpng $latestpng
fi

# link the latest png for easy access to web page
export latestpdf=$latestdir/T-latest.pdf
if [ -f  $latestpdf ] ; then
    sudo rm $latestpdf
fi    

export newestpdf=`ls -t $latestdir/T*.pdf | head -1`
#echo "Newest: " $newestpdf
if [ "$newestpdf" != "$latestpdf" ] ; then
    sudo ln -s $newestpdf $latestpdf
fi

#must touch the files to get them to refresh
sudo touch $latestpdf
sudo touch $latestpng
