#!/bin/bash
# plot the latest observation compared to latest hot
# HISTORY
# 21Jan18 GIL only process files in the "latest" dir
# 20Dec24 GIL check for files in data dir
# 20Nov12 GIL create latest file in html directory
# 20Jun16 GIL initial version that finds the latest observation
# find the most recent note file 

export binhome=/home/pi/Research/analyze
export latestdir="/var/www/html/latest"

cd $latestdir

sudo python $binhome/t.py -P ./ 3600. latest.hot latest.ast

export tlatest=`ls -t1 T-2?-??-??.png | head -1`
echo $tlatest
# now relink the T-latest plots
if [ "$tlatest"  != "" ] ; then 
    sudo rm -f T-latest.png
    sudo ln -s $latestdir/$tlatest T-latest.png 
fi

export tlatest=`ls -t1 T-2?-??-??.pdf | head -1`
echo $tlatest
# now relink the T-latest plots
if [ "$tlatest"  != "" ] ; then 
    sudo rm -f T-latest.pdf
    sudo ln -s $latestdir/$tlatest T-latest.pdf
fi
