#!/bin/bash
# plot the latest observation compared to latest hot
# HISTORY
# 21Jan19 GIL merge rawlatest and tsyslatest
# find the most recent note file 

export datadir=/home/pi/Research/gr-radio_astro/data
export lastestdir=/var/www/html/latest
export grhome=/home/pi/Research/gr-radio_astro

export binhome=/home/pi/Research/analyze
export latesthot=`$binhome/getlatesthot`
export latestobs=`$binhome/getlatestobs`
export latestdir="/var/www/html/latest"
# go to one directory above the data dir
cd $grhome
if [ "$latesthot" != "" ] ; then
    export latesthot=data/$latesthot
    sudo cp -f $latesthot $latestdir/latest.hot
fi
if [ "$latestobs" != "" ] ; then
    export latestobs=data/$latestobs
    sudo cp -f $latestobs $latestdir/latest.ast
fi

if [ "$latestobs" == "" ] && [ "$latesthot" == "" ] ; then
    exit
fi

cd $latestdir
echo $latesthot $latestobs
$binhome/R -P ./ *.hot *.ast

export newestpng=`ls -1 $latestdir/R-2*.png | tail -1`
#echo "Newest: " $newestpng
if [ "$newestpng" != "$latestpng" ] ; then 
    sudo mv -f $newestpng R-latest.png
fi

export newestpdf=`ls -1 $latestdir/R-2*.pdf | tail -1`
#echo "Newest: " $newestpdf
if [ "$newestpdf" != "$latestpdf" ] ; then 
    sudo mv -f $newestpdf R-latest.pdf
fi

# begin calibration plot after a short delay
sleep 5

sudo python $binhome/t.py -P ./ 600. *.hot *.ast

export tlatest=`ls -1 T-2?-??-??.png | tail -1`
echo $tlatest
# now relink the T-latest plots
if [ "$tlatest"  != "" ] ; then 
    sudo mv -f $tlatest T-latest.png 
fi

export tlatest=`ls -1 T-2?-??-??.pdf | tail -1`
echo $tlatest
# now relink the T-latest plots
if [ "$tlatest"  != "" ] ; then 
    sudo mv -f $tlatest T-latest.pdf
fi
